# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    hostname: ${DB_HOST}
    image: postgres:15.5
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    ports:
    - "${DB_PORT}"
    command: -p ${DB_PORT}
  app:
    build: .
    volumes:
      - .:/app/
    environment:
      DB_PORT: ${DB_PORT}
    ports:
    - "8000:${APP_PORT}"
  peek:
    image: debian:bookworm
    environment:
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
    tty: true
    stdin_open: true
    volumes:
      - ./scripts:/script
    command: >
      /bin/bash -c '
        apt update &&
        apt install -y postgresql-client-15 &&
        /bin/bash
      '